// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFOXs-svfXYMy7N-Tc4TplgiMa-_gaEfI',
    appId: '1:471326090855:web:8e76747fd20eb4638256c2',
    messagingSenderId: '471326090855',
    projectId: 'electricitymanagemantsystem',
    authDomain: 'electricitymanagemantsystem.firebaseapp.com',
    storageBucket: 'electricitymanagemantsystem.firebasestorage.app',
    measurementId: 'G-PY602067P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyN_V8Bzwtn9AlDKeBkT-7z41CAIg58Ok',
    appId: '1:471326090855:android:abafa331df1bcef68256c2',
    messagingSenderId: '471326090855',
    projectId: 'electricitymanagemantsystem',
    storageBucket: 'electricitymanagemantsystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSefVbYudvqrtUR9OSR6DQQaZAONCRP4',
    appId: '1:471326090855:ios:b266338a2b8f32418256c2',
    messagingSenderId: '471326090855',
    projectId: 'electricitymanagemantsystem',
    storageBucket: 'electricitymanagemantsystem.firebasestorage.app',
    iosBundleId: 'com.example.electricityManagemantSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFSefVbYudvqrtUR9OSR6DQQaZAONCRP4',
    appId: '1:471326090855:ios:b266338a2b8f32418256c2',
    messagingSenderId: '471326090855',
    projectId: 'electricitymanagemantsystem',
    storageBucket: 'electricitymanagemantsystem.firebasestorage.app',
    iosBundleId: 'com.example.electricityManagemantSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFOXs-svfXYMy7N-Tc4TplgiMa-_gaEfI',
    appId: '1:471326090855:web:5c015ac990cc125d8256c2',
    messagingSenderId: '471326090855',
    projectId: 'electricitymanagemantsystem',
    authDomain: 'electricitymanagemantsystem.firebaseapp.com',
    storageBucket: 'electricitymanagemantsystem.firebasestorage.app',
    measurementId: 'G-75YR41BR2V',
  );
}
